"""empty message

Revision ID: a1d8de87e237
Revises:
Create Date: 2022-07-31 00:56:21.823653+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1d8de87e237"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("strava_client_id", sa.Integer(), nullable=False),
        sa.Column("strava_secret", sa.String(), nullable=False),
        sa.Column("strava_refresh_token", sa.String(), nullable=True),
        sa.Column("strava_token", sa.String(), nullable=True),
        sa.Column(
            "strava_token_expiration", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strava_secret"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
