"""empty message

Revision ID: b7e72302637c
Revises:
Create Date: 2022-08-13 21:18:03.968763+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b7e72302637c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("rwgps_email", sa.String(), nullable=False),
        sa.Column("rwgps_password", sa.String(), nullable=False),
        sa.Column("rwgps_api_key", sa.String(), nullable=False),
        sa.Column("rwgps_token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rwgps_api_key"),
        sa.UniqueConstraint("rwgps_email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
